-- Seed 30 SKD CPNS questions (10 TWK + 10 TIU + 10 TKP)
-- Idempotent: ON CONFLICT DO NOTHING on id

BEGIN;

INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_001', 'TWK'::"Category", 'Pancasila', 'Nilai instrumental Pancasila berbeda dengan nilai dasar karena nilai instrumental bersifat...', '[{"label": "A", "text": "Abstrak, umum, dan tidak berubah sepanjang masa"}, {"label": "B", "text": "Lebih dinamis, kontekstual, dan dapat disesuaikan dengan perkembangan zaman"}, {"label": "C", "text": "Hanya berlaku bagi penyelenggara negara"}, {"label": "D", "text": "Tertulis dalam Pembukaan UUD 1945 secara eksplisit"}, {"label": "E", "text": "Mengikat lembaga internasional yang bekerja sama dengan Indonesia"}]'::jsonb, 'B', NULL, 3, 'Nilai dasar Pancasila bersifat abstrak dan tetap, sedangkan nilai instrumental merupakan penjabaran nilai dasar dalam bentuk peraturan perundang-undangan dan kebijakan yang lebih dinamis serta menyesuaikan perkembangan zaman.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_002', 'TWK'::"Category", 'UUD 1945', 'Pasal 1 ayat (3) UUD 1945 menegaskan bahwa Indonesia adalah negara hukum. Konsekuensi langsung dari ketentuan ini adalah...', '[{"label": "A", "text": "Setiap kebijakan presiden tidak dapat diuji oleh lembaga manapun"}, {"label": "B", "text": "Hukum adat dihapuskan dari sistem hukum nasional"}, {"label": "C", "text": "Segala tindakan penyelenggara negara harus berdasarkan hukum yang berlaku"}, {"label": "D", "text": "Mahkamah Agung berhak membuat undang-undang"}, {"label": "E", "text": "Warga negara dapat mengabaikan peraturan daerah"}]'::jsonb, 'C', NULL, 2, 'Sebagai negara hukum (rechtsstaat), seluruh tindakan penyelenggara negara harus berdasarkan hukum yang berlaku, serta setiap warga negara memiliki kedudukan yang sama di hadapan hukum.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_003', 'TWK'::"Category", 'Bhinneka Tunggal Ika', 'Semboyan Bhinneka Tunggal Ika diambil dari Kitab Sutasoma karya Mpu Tantular. Makna paling tepat dari semboyan ini dalam konteks NKRI adalah...', '[{"label": "A", "text": "Keberagaman harus dihilangkan demi persatuan"}, {"label": "B", "text": "Berbeda-beda tetapi tetap satu jua dalam bingkai persatuan Indonesia"}, {"label": "C", "text": "Hanya satu agama yang diakui sebagai pemersatu bangsa"}, {"label": "D", "text": "Suku mayoritas memiliki hak istimewa dalam pemerintahan"}, {"label": "E", "text": "Persatuan hanya berlaku di tingkat pusat, bukan daerah"}]'::jsonb, 'B', NULL, 1, 'Bhinneka Tunggal Ika berarti berbeda-beda tetapi tetap satu jua. Semboyan ini menegaskan bahwa keberagaman suku, agama, ras, dan budaya tetap dipersatukan dalam bingkai NKRI.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_004', 'TWK'::"Category", 'NKRI', 'Wawasan Nusantara sebagai cara pandang bangsa Indonesia terhadap diri dan lingkungannya menempatkan wilayah Indonesia sebagai...', '[{"label": "A", "text": "Kumpulan pulau yang berdiri sendiri-sendiri"}, {"label": "B", "text": "Satu kesatuan politik, ekonomi, sosial budaya, dan pertahanan keamanan"}, {"label": "C", "text": "Wilayah yang hanya mengutamakan kepentingan pulau Jawa"}, {"label": "D", "text": "Kawasan yang terbuka tanpa batas teritorial"}, {"label": "E", "text": "Daerah otonom yang lepas dari pemerintah pusat"}]'::jsonb, 'B', NULL, 2, 'Wawasan Nusantara menempatkan wilayah Indonesia sebagai satu kesatuan politik, ekonomi, sosial budaya, serta pertahanan dan keamanan, sehingga seluruh wilayah dipandang sebagai satu kesatuan utuh.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_005', 'TWK'::"Category", 'Sejarah Kemerdekaan', 'Peristiwa Rengasdengklok pada 16 Agustus 1945 memiliki arti penting karena...', '[{"label": "A", "text": "Merupakan tempat penandatanganan naskah proklamasi"}, {"label": "B", "text": "Mendesak Soekarno-Hatta segera memproklamasikan kemerdekaan tanpa menunggu Jepang"}, {"label": "C", "text": "Menjadi lokasi pembentukan PPKI"}, {"label": "D", "text": "Tempat perundingan Indonesia dengan Sekutu"}, {"label": "E", "text": "Awal dimulainya Agresi Militer Belanda I"}]'::jsonb, 'B', NULL, 3, 'Peristiwa Rengasdengklok adalah tindakan golongan muda yang membawa Soekarno-Hatta ke Rengasdengklok untuk mendesak agar proklamasi kemerdekaan segera dilakukan tanpa menunggu sidang PPKI atau campur tangan Jepang.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_006', 'TWK'::"Category", 'Pancasila', 'Sikap yang mencerminkan pengamalan sila keempat Pancasila dalam kehidupan bermasyarakat adalah...', '[{"label": "A", "text": "Memaksakan pendapat pribadi dalam rapat warga karena merasa paling benar"}, {"label": "B", "text": "Menyelesaikan perbedaan pendapat melalui musyawarah untuk mencapai mufakat"}, {"label": "C", "text": "Mengambil keputusan secara sepihak demi efisiensi"}, {"label": "D", "text": "Hanya mendengarkan suara mayoritas tanpa pertimbangan minoritas"}, {"label": "E", "text": "Menolak hadir dalam pertemuan warga karena sibuk"}]'::jsonb, 'B', NULL, 2, 'Sila keempat Pancasila menekankan kerakyatan yang dipimpin oleh hikmat kebijaksanaan dalam permusyawaratan/perwakilan, sehingga pengambilan keputusan dilakukan melalui musyawarah untuk mufakat dengan menghargai semua pihak.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_007', 'TWK'::"Category", 'UUD 1945', 'Amandemen UUD 1945 yang menghasilkan pembatasan masa jabatan Presiden dan Wakil Presiden menjadi maksimal dua periode terjadi pada amandemen ke-...', '[{"label": "A", "text": "Pertama (1999)"}, {"label": "B", "text": "Kedua (2000)"}, {"label": "C", "text": "Ketiga (2001)"}, {"label": "D", "text": "Keempat (2002)"}, {"label": "E", "text": "Kelima (belum dilakukan)"}]'::jsonb, 'A', NULL, 3, 'Amandemen pertama UUD 1945 pada tahun 1999 antara lain mengubah Pasal 7 sehingga membatasi masa jabatan Presiden dan Wakil Presiden hanya untuk dua kali masa jabatan.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_008', 'TWK'::"Category", 'Bela Negara', 'Bentuk usaha bela negara yang dapat dilakukan oleh seorang aparatur sipil negara dalam menjalankan tugasnya adalah...', '[{"label": "A", "text": "Menerima gratifikasi demi kelancaran pekerjaan"}, {"label": "B", "text": "Memberikan pelayanan publik secara profesional, jujur, dan berintegritas"}, {"label": "C", "text": "Menghindari pekerjaan yang sulit"}, {"label": "D", "text": "Mengutamakan kepentingan kelompok tertentu"}, {"label": "E", "text": "Menyebarkan informasi rahasia negara di media sosial"}]'::jsonb, 'B', NULL, 2, 'Bela negara dalam konteks ASN diwujudkan melalui pelaksanaan tugas secara profesional, jujur, berintegritas, serta mengutamakan kepentingan bangsa dan negara di atas kepentingan pribadi atau golongan.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_009', 'TWK'::"Category", 'Nasionalisme', 'Nasionalisme yang dianut bangsa Indonesia adalah nasionalisme Pancasila yang bersifat...', '[{"label": "A", "text": "Chauvinistik dan menempatkan bangsa sendiri di atas bangsa lain"}, {"label": "B", "text": "Sempit dan menutup diri dari pergaulan internasional"}, {"label": "C", "text": "Terbuka, menjunjung persamaan derajat, serta menghormati bangsa lain"}, {"label": "D", "text": "Eksklusif untuk kelompok mayoritas saja"}, {"label": "E", "text": "Menolak segala bentuk kerja sama dengan negara lain"}]'::jsonb, 'C', NULL, 2, 'Nasionalisme Pancasila bersifat terbuka, mencintai bangsa sendiri tanpa merendahkan bangsa lain, serta menjunjung tinggi persamaan derajat dan kerja sama internasional sebagaimana diamanatkan Pembukaan UUD 1945.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_twk_010', 'TWK'::"Category", 'Integritas', 'Seorang pejabat publik menerima tawaran perjalanan dinas mewah dari rekanan proyek yang sedang ditangani instansinya. Sikap yang mencerminkan integritas adalah...', '[{"label": "A", "text": "Menerima tawaran karena dianggap bagian dari relasi kerja"}, {"label": "B", "text": "Menerima tetapi melaporkannya sebagai gratifikasi setelah kegiatan selesai bertahun kemudian"}, {"label": "C", "text": "Menolak tawaran tersebut dan melaporkan kepada atasan serta unit pengendalian gratifikasi"}, {"label": "D", "text": "Menerima dengan syarat keluarga juga diikutsertakan"}, {"label": "E", "text": "Mengalihkan tawaran tersebut kepada rekan kerja yang lain"}]'::jsonb, 'C', NULL, 3, 'Pejabat publik wajib menjaga integritas dengan menolak segala bentuk gratifikasi yang berhubungan dengan jabatan dan berlawanan dengan tugasnya, serta melaporkannya kepada atasan dan KPK/unit pengendalian gratifikasi sesuai UU Tipikor.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_001', 'TIU'::"Category", 'Verbal Sinonim', 'ABOLISI memiliki makna yang sama dengan ...', '[{"label": "A", "text": "Pengurangan"}, {"label": "B", "text": "Penghapusan"}, {"label": "C", "text": "Pengampunan"}, {"label": "D", "text": "Penambahan"}, {"label": "E", "text": "Penundaan"}]'::jsonb, 'B', NULL, 3, 'Abolisi berarti penghapusan atau peniadaan peristiwa pidana. Berbeda dengan grasi (pengampunan) atau amnesti.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_002', 'TIU'::"Category", 'Verbal Antonim', 'Lawan kata dari KONVEKS adalah ...', '[{"label": "A", "text": "Cembung"}, {"label": "B", "text": "Datar"}, {"label": "C", "text": "Cekung"}, {"label": "D", "text": "Lurus"}, {"label": "E", "text": "Bengkok"}]'::jsonb, 'C', NULL, 2, 'Konveks berarti cembung, sehingga lawan katanya adalah konkaf yang berarti cekung.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_003', 'TIU'::"Category", 'Verbal Analogi', 'DOKTER : STETOSKOP = TUKANG KAYU : ...', '[{"label": "A", "text": "Paku"}, {"label": "B", "text": "Kayu"}, {"label": "C", "text": "Gergaji"}, {"label": "D", "text": "Meja"}, {"label": "E", "text": "Bengkel"}]'::jsonb, 'C', NULL, 1, 'Stetoskop adalah alat yang digunakan dokter untuk bekerja. Analoginya, gergaji adalah alat yang digunakan tukang kayu untuk bekerja.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_004', 'TIU'::"Category", 'Numerik Deret', 'Tentukan dua bilangan selanjutnya dari deret: 3, 6, 12, 24, 48, ...', '[{"label": "A", "text": "96, 192"}, {"label": "B", "text": "72, 96"}, {"label": "C", "text": "96, 144"}, {"label": "D", "text": "60, 72"}, {"label": "E", "text": "84, 168"}]'::jsonb, 'A', NULL, 2, 'Setiap suku dikalikan 2 dari suku sebelumnya. Maka 48×2 = 96 dan 96×2 = 192.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_005', 'TIU'::"Category", 'Numerik Aritmatika', 'Jika 3/5 dari sebuah bilangan adalah 60, maka 2/3 dari bilangan tersebut adalah ...', '[{"label": "A", "text": "60"}, {"label": "B", "text": "66"}, {"label": "C", "text": "66 2/3"}, {"label": "D", "text": "70"}, {"label": "E", "text": "75"}]'::jsonb, 'C', NULL, 3, 'Bilangan = 60 × 5/3 = 100. Maka 2/3 × 100 = 200/3 = 66 2/3.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_006', 'TIU'::"Category", 'Numerik Soal Cerita', 'Sebuah barang dijual dengan harga Rp120.000 dan penjual memperoleh untung 20% dari harga beli. Berapa harga beli barang tersebut?', '[{"label": "A", "text": "Rp96.000"}, {"label": "B", "text": "Rp100.000"}, {"label": "C", "text": "Rp104.000"}, {"label": "D", "text": "Rp108.000"}, {"label": "E", "text": "Rp110.000"}]'::jsonb, 'B', NULL, 2, 'Harga jual = 120% × harga beli. 120.000 = 1,2 × HB, maka HB = 100.000.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_007', 'TIU'::"Category", 'Numerik Perbandingan', 'Sebuah pekerjaan dapat diselesaikan oleh 12 pekerja dalam waktu 15 hari. Jika ditambah 3 pekerja lagi, dalam berapa hari pekerjaan tersebut akan selesai?', '[{"label": "A", "text": "10 hari"}, {"label": "B", "text": "11 hari"}, {"label": "C", "text": "12 hari"}, {"label": "D", "text": "13 hari"}, {"label": "E", "text": "14 hari"}]'::jsonb, 'C', NULL, 3, 'Perbandingan berbalik nilai: 12 × 15 = 15 × x, maka x = 180/15 = 12 hari.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_008', 'TIU'::"Category", 'Logika Penalaran', 'Semua siswa kelas A mengikuti ekstrakurikuler. Sebagian siswa kelas A mengikuti pramuka. Kesimpulan yang tepat adalah ...', '[{"label": "A", "text": "Semua siswa kelas A mengikuti pramuka"}, {"label": "B", "text": "Sebagian siswa yang mengikuti pramuka adalah kelas A"}, {"label": "C", "text": "Sebagian siswa kelas A mengikuti ekstrakurikuler selain pramuka"}, {"label": "D", "text": "Tidak ada siswa kelas A yang tidak mengikuti pramuka"}, {"label": "E", "text": "Semua siswa pramuka berasal dari kelas A"}]'::jsonb, 'C', NULL, 3, 'Karena hanya sebagian siswa kelas A yang mengikuti pramuka, sementara semuanya mengikuti ekstrakurikuler, maka sebagian lainnya pasti mengikuti ekstrakurikuler selain pramuka.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_009', 'TIU'::"Category", 'Logika Silogisme', 'Semua dokter adalah lulusan universitas. Sebagian lulusan universitas bekerja di rumah sakit. Kesimpulan yang tepat adalah ...', '[{"label": "A", "text": "Semua dokter bekerja di rumah sakit"}, {"label": "B", "text": "Sebagian dokter bekerja di rumah sakit"}, {"label": "C", "text": "Semua yang bekerja di rumah sakit adalah dokter"}, {"label": "D", "text": "Sebagian lulusan universitas adalah dokter yang bekerja di rumah sakit"}, {"label": "E", "text": "Tidak dapat ditarik kesimpulan pasti"}]'::jsonb, 'E', NULL, 4, 'Premis pertama bersifat universal, premis kedua partikular. Tidak ada kaitan langsung yang memastikan dokter termasuk dalam sebagian lulusan yang bekerja di rumah sakit, sehingga kesimpulan tidak dapat ditarik secara pasti.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tiu_010', 'TIU'::"Category", 'Figural Geometri', 'Sebuah persegi memiliki panjang sisi 8 cm. Jika sisinya diperpanjang 25%, maka luas persegi yang baru adalah ...', '[{"label": "A", "text": "80 cm²"}, {"label": "B", "text": "96 cm²"}, {"label": "C", "text": "100 cm²"}, {"label": "D", "text": "120 cm²"}, {"label": "E", "text": "144 cm²"}]'::jsonb, 'C', NULL, 3, 'Sisi baru = 8 + 25% × 8 = 10 cm. Luas baru = 10 × 10 = 100 cm².', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_001', 'TKP'::"Category", 'Pelayanan publik', 'Anda bertugas di loket layanan publik. Antrian sangat panjang dan beberapa pemohon mulai mengeluh keras karena lama menunggu. Sikap Anda...', '[{"label": "A", "text": "Tetap melayani sesuai prosedur sambil menjelaskan kondisi dengan tenang dan empatik kepada pemohon."}, {"label": "B", "text": "Mempercepat layanan dengan tetap menjaga akurasi, meminta dukungan rekan, dan memberi informasi estimasi waktu kepada pemohon."}, {"label": "C", "text": "Fokus bekerja dan mengabaikan keluhan agar antrian segera berkurang."}, {"label": "D", "text": "Meminta pemohon yang marah untuk pulang dan kembali esok hari saat kondisi lebih sepi."}, {"label": "E", "text": "Menjelaskan kondisi kepada pemohon dan menawarkan alternatif layanan daring bila tersedia."}]'::jsonb, 'B', '{"A": 3, "B": 5, "C": 2, "D": 1, "E": 4}'::jsonb, 2, 'Opsi B paling ideal karena menyeimbangkan kecepatan, akurasi, kolaborasi, dan komunikasi proaktif kepada pemohon, sesuai prinsip pelayanan prima ASN.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_002', 'TKP'::"Category", 'Jejaring kerja', 'Anda mengoordinasikan proyek lintas instansi, namun instansi mitra lambat merespons permintaan data yang Anda butuhkan untuk memenuhi tenggat. Tindakan Anda...', '[{"label": "A", "text": "Mengirim surat resmi pengingat dan menunggu balasan formal dari instansi mitra."}, {"label": "B", "text": "Menghubungi contact person instansi mitra untuk mengonfirmasi kendala dan menyusun solusi bersama."}, {"label": "C", "text": "Melaporkan ke atasan bahwa proyek terhambat karena keterlambatan instansi mitra."}, {"label": "D", "text": "Menggunakan jaringan informal untuk menanyakan langsung kepada pejabat di instansi mitra."}, {"label": "E", "text": "Menunggu hingga mendekati tenggat lalu baru menindaklanjuti agar mereka terdesak."}]'::jsonb, 'B', '{"A": 3, "B": 5, "C": 2, "D": 4, "E": 1}'::jsonb, 3, 'Opsi B paling ideal karena menumbuhkan komunikasi dua arah, mengidentifikasi hambatan nyata, dan membangun solusi kolaboratif yang menjadi inti membangun jejaring kerja.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_003', 'TKP'::"Category", 'Sosial budaya', 'Tim Anda kedatangan rekan baru dari daerah dengan budaya yang berbeda. Beberapa kebiasaannya membuat sebagian anggota tim merasa canggung. Sikap Anda...', '[{"label": "A", "text": "Mengabaikan perbedaan dan tetap fokus pada pekerjaan masing-masing."}, {"label": "B", "text": "Mengajak rekan tersebut berbincang santai untuk saling mengenal dan memahami latar belakangnya."}, {"label": "C", "text": "Mendiskusikan bersama tim cara menyesuaikan komunikasi agar suasana lebih inklusif bagi semua anggota."}, {"label": "D", "text": "Meminta atasan memindahkannya ke tim lain agar tidak mengganggu dinamika kerja."}, {"label": "E", "text": "Memberitahu rekan tersebut secara langsung bahwa kebiasaannya tidak cocok di lingkungan kantor ini."}]'::jsonb, 'C', '{"A": 3, "B": 4, "C": 5, "D": 1, "E": 2}'::jsonb, 3, 'Opsi C paling ideal karena menumbuhkan inklusivitas secara kolektif, menghormati keberagaman, dan menjaga kohesi tim sesuai nilai Bhinneka Tunggal Ika.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_004', 'TKP'::"Category", 'Teknologi informasi', 'Kantor Anda baru saja menerapkan aplikasi pelaporan kinerja berbasis daring. Anda kesulitan menggunakannya karena tidak terbiasa. Sikap Anda...', '[{"label": "A", "text": "Bertanya kepada rekan kerja yang sudah mahir untuk dipandu langkah demi langkah."}, {"label": "B", "text": "Mempelajari panduan resmi dan mengikuti pelatihan yang disediakan kantor secara mandiri."}, {"label": "C", "text": "Tetap memakai cara manual seperti biasa karena merasa lebih nyaman dan akurat."}, {"label": "D", "text": "Mengisi laporan seadanya yang penting terkirim ke sistem tepat waktu."}, {"label": "E", "text": "Meminta rekan kerja mengisikan laporan Anda sambil Anda mengamati prosesnya."}]'::jsonb, 'B', '{"A": 4, "B": 5, "C": 3, "D": 1, "E": 2}'::jsonb, 2, 'Opsi B paling ideal karena menumbuhkan kemandirian digital secara berkelanjutan melalui sumber resmi, sesuai tuntutan literasi TIK ASN modern.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_005', 'TKP'::"Category", 'Profesionalisme', 'Menjelang jam pulang, atasan memberi tugas mendadak yang harus selesai malam ini, sementara Anda masih memiliki tugas lain yang belum tuntas. Sikap Anda...', '[{"label": "A", "text": "Menyanggupi dan menyelesaikan tugas tersebut malam ini meski harus lembur panjang."}, {"label": "B", "text": "Mengonfirmasi urgensi dan memprioritaskan ulang bersama atasan dengan mempertimbangkan tugas yang sedang berjalan."}, {"label": "C", "text": "Menolak karena sudah lewat jam kerja dan ada tugas lain yang belum selesai."}, {"label": "D", "text": "Menyelesaikan secara cepat dengan kualitas seadanya agar bisa pulang tepat waktu."}, {"label": "E", "text": "Membawanya pulang dan mengerjakan bila sempat di rumah."}]'::jsonb, 'B', '{"A": 4, "B": 5, "C": 1, "D": 2, "E": 3}'::jsonb, 3, 'Opsi B paling ideal karena profesional ASN berkomunikasi terbuka dengan atasan untuk menetapkan prioritas tanpa mengorbankan kualitas pekerjaan lain.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_006', 'TKP'::"Category", 'Anti radikalisme', 'Anda mendapati seorang rekan kerja kerap mengunggah konten yang mengarah pada intoleransi dan ujaran kebencian terhadap kelompok tertentu di media sosial. Sikap Anda...', '[{"label": "A", "text": "Mengabaikan karena hal itu merupakan urusan pribadi rekan kerja di luar jam kantor."}, {"label": "B", "text": "Mengajaknya bicara empat mata untuk mengingatkan dampak unggahannya bagi citra ASN."}, {"label": "C", "text": "Melaporkan ke atasan dan unit kepegawaian sesuai prosedur internal yang berlaku."}, {"label": "D", "text": "Membalas unggahannya di kolom komentar untuk berdebat secara terbuka."}, {"label": "E", "text": "Memutus pertemanan di media sosial tanpa memberitahu apa pun kepadanya."}]'::jsonb, 'C', '{"A": 1, "B": 4, "C": 5, "D": 2, "E": 3}'::jsonb, 4, 'Opsi C paling ideal karena ASN wajib menjaga netralitas dan persatuan; intoleransi memerlukan tindakan formal melalui saluran resmi sesuai kode etik ASN.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_007', 'TKP'::"Category", 'Pelayanan publik', 'Seorang penyandang disabilitas datang mengurus dokumen di kantor Anda, namun memerlukan bantuan khusus yang belum diatur dalam SOP layanan. Sikap Anda...', '[{"label": "A", "text": "Membantu sesuai kemampuan dan berkoordinasi dengan rekan serta atasan untuk mencari solusi terbaik bagi pemohon."}, {"label": "B", "text": "Meminta pemohon kembali lain hari dengan membawa pendamping yang dapat membantunya."}, {"label": "C", "text": "Menolak melayani karena bantuan tersebut tidak diatur dalam SOP yang berlaku."}, {"label": "D", "text": "Membantu sebisanya lalu mengarahkan pemohon ke loket lain yang mungkin lebih sesuai."}, {"label": "E", "text": "Memproses dokumen seadanya tanpa memberi bantuan tambahan agar tidak melampaui kewenangan."}]'::jsonb, 'A', '{"A": 5, "B": 3, "C": 1, "D": 4, "E": 2}'::jsonb, 3, 'Opsi A paling ideal karena pelayanan publik wajib inklusif dan responsif terhadap kelompok rentan; berkoordinasi memastikan solusi tepat tanpa melanggar aturan.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_008', 'TKP'::"Category", 'Profesionalisme', 'Atasan meminta Anda menyusun laporan kegiatan dengan angka yang Anda ketahui tidak sesuai kondisi sebenarnya di lapangan. Sikap Anda...', '[{"label": "A", "text": "Menyusun laporan sesuai permintaan atasan demi menjaga hubungan baik dan kelancaran karier."}, {"label": "B", "text": "Menyampaikan kepada atasan data sebenarnya beserta risiko jika dimanipulasi, lalu menawarkan alternatif penyajian yang akurat."}, {"label": "C", "text": "Menolak mengerjakan laporan tersebut karena bertentangan dengan prinsip kejujuran."}, {"label": "D", "text": "Mengerjakan laporan menggunakan data sebenarnya tanpa mengonfirmasi ulang kepada atasan."}, {"label": "E", "text": "Menyusun laporan dengan kalimat ambigu yang bisa ditafsirkan ke berbagai arah."}]'::jsonb, 'B', '{"A": 1, "B": 5, "C": 3, "D": 4, "E": 2}'::jsonb, 4, 'Opsi B paling ideal karena menjaga integritas data sekaligus menghormati hierarki dengan dialog terbuka, sesuai nilai akuntabilitas ASN.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_009', 'TKP'::"Category", 'Jejaring kerja', 'Dalam rapat tim, Anda berbeda pendapat tajam dengan seorang rekan mengenai strategi kerja, dan diskusi mulai memanas. Sikap Anda...', '[{"label": "A", "text": "Tetap mempertahankan pendapat dengan tegas dan menyanggah setiap argumen rekan tersebut."}, {"label": "B", "text": "Mengusulkan jeda singkat lalu berdiskusi secara privat dengan rekan untuk mencari titik temu."}, {"label": "C", "text": "Mengalah agar rapat segera selesai meskipun pandangan profesional Anda berbeda."}, {"label": "D", "text": "Menyampaikan pendapat dengan data pendukung yang relevan dan terbuka pada masukan rekan."}, {"label": "E", "text": "Diam selama rapat lalu melobi peserta lain di luar forum agar mendukung pendapat Anda."}]'::jsonb, 'D', '{"A": 1, "B": 4, "C": 2, "D": 5, "E": 3}'::jsonb, 3, 'Opsi D paling ideal karena membangun jejaring kerja yang sehat membutuhkan argumentasi berbasis data dan kesediaan menerima masukan secara profesional.', 'original') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, category, subcategory, "questionText", options, "correctAnswer", "optionWeights", difficulty, explanation, source) VALUES ('q_tkp_010', 'TKP'::"Category", 'Sosial budaya', 'Tim Anda akan menyelenggarakan acara syukuran kantor, namun terdapat anggota tim yang memiliki agama dan kebiasaan berbeda dari mayoritas. Sikap Anda...', '[{"label": "A", "text": "Mengadakan acara mengikuti kebiasaan mayoritas anggota tim agar lebih praktis."}, {"label": "B", "text": "Menyusun konsep acara inklusif yang mempertimbangkan kenyamanan seluruh anggota tim."}, {"label": "C", "text": "Mengajak seluruh anggota tim berdiskusi untuk merancang format acara bersama."}, {"label": "D", "text": "Mengadakan dua acara terpisah sesuai kelompok agar setiap orang merasa nyaman."}, {"label": "E", "text": "Membatalkan acara untuk menghindari potensi kesalahpahaman antarpegawai."}]'::jsonb, 'C', '{"A": 2, "B": 4, "C": 5, "D": 3, "E": 1}'::jsonb, 3, 'Opsi C paling ideal karena menumbuhkan rasa saling memiliki melalui partisipasi seluruh anggota, sekaligus menghormati keberagaman sesuai nilai Bhinneka Tunggal Ika.', 'original') ON CONFLICT (id) DO NOTHING;

-- Enable RLS policies for runtime app

ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE attempt_items ENABLE ROW LEVEL SECURITY;

-- Public read on questions (any user can fetch tryout questions)
DROP POLICY IF EXISTS "public read questions" ON questions;
CREATE POLICY "public read questions" ON questions FOR SELECT USING (true);

-- Users: can read/insert/update own row
DROP POLICY IF EXISTS "users self select" ON users;
CREATE POLICY "users self select" ON users FOR SELECT USING (auth.uid()::text = id OR id LIKE 'anon_%');
DROP POLICY IF EXISTS "users self insert" ON users;
CREATE POLICY "users self insert" ON users FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "users self update" ON users;
CREATE POLICY "users self update" ON users FOR UPDATE USING (auth.uid()::text = id);

-- Attempts: anyone can create + read attempts (anonymous tryout flow)
DROP POLICY IF EXISTS "anyone create attempts" ON attempts;
CREATE POLICY "anyone create attempts" ON attempts FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "public read attempts" ON attempts;
CREATE POLICY "public read attempts" ON attempts FOR SELECT USING (true);
DROP POLICY IF EXISTS "anyone update attempts" ON attempts;
CREATE POLICY "anyone update attempts" ON attempts FOR UPDATE USING (true);

-- Attempt items: same permissive policy for MVP
DROP POLICY IF EXISTS "anyone create attempt_items" ON attempt_items;
CREATE POLICY "anyone create attempt_items" ON attempt_items FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "public read attempt_items" ON attempt_items;
CREATE POLICY "public read attempt_items" ON attempt_items FOR SELECT USING (true);
DROP POLICY IF EXISTS "anyone update attempt_items" ON attempt_items;
CREATE POLICY "anyone update attempt_items" ON attempt_items FOR UPDATE USING (true);

-- Cleanup test row
DELETE FROM questions WHERE id = 'test-1';

COMMIT;

-- Verify
SELECT category, COUNT(*) FROM questions GROUP BY category ORDER BY category;