// Types matching docs/content/SCHEMA-OUTPUT.md
// Generated by scripts/content-to-json.ts

export type Category = "TWK" | "TIU" | "TKP";

export interface QuestionOption {
  label: "A" | "B" | "C" | "D" | "E";
  text: string;
}

export interface OptionWeights {
  A: number;
  B: number;
  C: number;
  D: number;
  E: number;
}

export interface LabQuestion {
  id: string;
  category: Category;
  subcategory: string;
  topic: string;
  questionText: string;
  options: QuestionOption[];
  correctAnswer: "A" | "B" | "C" | "D" | "E";
  optionWeights: OptionWeights | null; // TKP only
  difficulty: 1 | 2 | 3 | 4 | 5;
  tags: string[];
  familyId: string | null;
  enemyGroupId: string | null;
  imagePrompt: string | null; // Figural only
  explanation: string;
  explanationLong: string;
  source: string;
  warnings: string[];
}

export interface BatchStats {
  total_soal: number;
  by_difficulty: Record<string, number>;
  warnings_total: number;
}

export interface LabBatch {
  batch_id: string;
  topic: string;
  source_file: string;
  generated_at: string;
  stats: BatchStats;
  questions: LabQuestion[];
}

export interface BatchSummary {
  batch_id: string;
  topic: string;
  category: Category | "MIXED";
  total_soal: number;
  difficulty_avg: number;
  warnings: number;
}
